
// User

const USER_AUTH_REQUESTED = 'USER_AUTH_REQUESTED';
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';

// Schedule

const FETCH_SCHEDULE_REQUESTED = 'FETCH_SCHEDULE_REQUESTED';
const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
const FETCH_SCHEDULE_FAILURE = 'FETCH_SCHEDULE_FAILURE';

// Chat

const FETCH_CHAT_MESSAGES_REQUESTED = 'FETCH_CHAT_MESSAGES_REQUESTED';
const FETCH_CHAT_MESSAGES_SUCCESS = 'FETCH_CHAT_MESSAGES_SUCCESS';
const FETCH_CHAT_MESSAGES_FAILURE = 'FETCH_CHAT_MESSAGES_FAILURE';

const SEND_MESSAGE = 'SEND_MESSAGE';

export {
  USER_AUTH_REQUESTED,
  USER_AUTH_SUCCESS,
  USER_AUTH_FAILURE,
  FETCH_SCHEDULE_REQUESTED,
  FETCH_SCHEDULE_SUCCESS,
  FETCH_SCHEDULE_FAILURE,
  FETCH_CHAT_MESSAGES_REQUESTED,
  FETCH_CHAT_MESSAGES_SUCCESS,
  FETCH_CHAT_MESSAGES_FAILURE,
  SEND_MESSAGE
}